name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: hzywind
        password: ${{ secrets.DOCKERHUB_KEY }}
    - name: Build the Docker image
      run: docker buildx build . --file Dockerfile --tag hzywind/nginx-njs-acme:1.24.0
    - name: Push the Docker image
      run: docker push hzywind/nginx-njs-acme:1.24.0
